# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]   
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create Download Directory
      run: mkdir downloads
      
    - name: Create docs
      run: |
        python -m pydoc -w ./
        mv *.html ./downloads
    - name: upload documents
      uses: actions/upload-artifact@v2
      with:
        name: assetDocuments
        path: downloads

    - name: download workflow artifact
      uses: benday-inc/download-latest-artifact@main
      with:
        token: ${{ secrets.ACTION_SECRET }}'
        repository_owner: 'Lowkh'
        repository_name: 'ETITestCode'
        workflow_name: 'Python Documentation'  
        branch_name: 'main'
        download_path: '${{ github.workspace }}/downloads'
        download_filename: 'assetDocuments.zip'
