on:
  create:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: RalfG/python-wheels-manylinux-build@v0.2.2
        with:
          python-versions: 'cp36-cp36m cp37-cp37m'
